- name: Create Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
  - include_vars: vars.yml

  - name: Create resource group - "{{ resource_group }}" in "{{ location }}"
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Create virtual network - "{{ vnet }}"
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vnet }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet - "{{ subnet }}"
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vnet }}"
      
  - name: Create public IP address - "{{ public_ip }}"
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ network_security_group }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create virtual network interface card - "{{ vnic }}"
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vnic }}"
      virtual_network: "{{ vnet }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ public_ip }}"
      security_group: "{{ network_security_group }}"

  - name: Create Storage account 
    azure.azcollection.azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storage_account }}"
      account_type: Standard_LRS

  - name: Create VM - "{{ vm_name }}"
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard_DS1_v2
      admin_username: "{{ admin_username }}"
      ssh_password_enabled: false
      storage_account_name: "{{ storage_account }}"
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ key_data }}"
      network_interfaces: "{{ vnic }}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest